c:
	npx hardhat compile
t:
	npx hardhat test
clean:
	npx hardhat clean
deploy-token:
	npx hardhat ignition deploy ./ignition/modules/OnbaordXToken.ts --network lisk-sepolia --verify
deploy-contract:
	npx hardhat ignition deploy ./ignition/modules/OnboardX.ts --network lisk-sepolia --verify
clean:
	npx hardhat clean




	
